project/recipes/forms.py
# project/recipes/forms.py
 
 
from flask_wtf import Form
from wtforms import StringField
from wtforms.validators import DataRequired
 
 
class AddRecipeForm(Form):
    recipe_title = StringField('Recipe Title', validators=[DataRequired()])
    recipe_description = StringField('Recipe Description', validators=[DataRequired()])

project/recipes/views.py
#################
#### imports ####
#################
 
from flask import render_template, request, redirect, url_for, Blueprint, flash, current_app as app
from project import db
from project.models import Recipe
from .forms import AddRecipeForm
 
 
################
#### config ####
################
 
recipes_blueprint = Blueprint('recipes', __name__, template_folder='templates')
 
##########################
#### helper functions ####
##########################

def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (
                getattr(form, field).label.text,
                error
            ), 'info')

################
#### routes ####
################
 
 
@recipes_blueprint.route('/')
def all():
    app.logger.debug("call all recipes")
    all_recipes = Recipe.query.all()
    return render_template('recipes.html', recipes=all_recipes)
    
@recipes_blueprint.route('/public_recipes/')
def public_recipes():
    all_public_recipes = Recipe.query.filter_by(is_public=True)
    return render_template('public_recipes.html', public_recipes=all_public_recipes)    
    
@recipes_blueprint.route('/recipe/<userid>')
def recipe(userid):
    all_user_recipes = Recipe.query.filter_by(user_id=userid)
    return render_template('user_recipes.html', user_recipes=all_user_recipes)    
    
@recipes_blueprint.route('/add', methods=['GET', 'POST'])
def add_recipe():
    form = AddRecipeForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_recipe = Recipe(form.recipe_title.data, form.recipe_description.data, 2, True)
            db.session.add(new_recipe)
            db.session.commit()
            flash('New recipe, {}, added!'.format(new_recipe.recipe_title), 'success')
            return redirect(url_for('recipes.index'))
        else:
            flash_errors(form)
            flash('ERROR! Recipe was not added.', 'error')
 
    return render_template('add_recipe.html',
                           form=form)    

project/recipes/templates/_form_macros.html
{% macro render_field(field) %}
 
<dt>{{ field.label }}:
 
<dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
</dd>
 
 
{% endmacro %}

project/recipes/templates/add_recipe.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}
 
{% block content %}
 
 
<div class="add-recipe">
 
<div class="page-header">
 
<h2>Add a New Recipe</h2>
 
  </div>
 
 
 
<form action="{{ url_for('recipes.add_recipe') }}" method="post">
    {{ form.csrf_token }}
 
<dl>
      {{ render_field(form.recipe_title, placeholder="Enter Recipe Title") }}
      {{ render_field(form.recipe_description, placeholder="Enter Recipe Description") }}
    </dl>
 
    <button class="btn btn-sm btn-success" type="submit">Add Recipe</button>
  </form>
 
</div>
 
 
{% endblock %}

project/recipes/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Kennedy Family Recipe App">
    <meta name="author" content="Patrick Kennedy">
    <title>Kennedy Family Recipe App</title>
    <!-- styles -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}"> 
  </head>

  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#recipes-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <a class="navbar-brand" href="{{ url_for('recipes.public_recipes') }}">Kennedy Family Recipes</a>            
          </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="recipes-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="#">Breakfast Recipes</a></li>
            <li><a href="#">Lunch Recipes</a></li>
            <li><a href="#">Dinner Recipes</a></li>
            <li><a href="#">Dessert Recipes</a></li>
            <li><a href="{{ url_for('recipes.add_recipe') }}">Add Recipe</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Welcome!</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div><!-- /.container -->
    </nav>

    <div class="container">
      <div class="content">

        <!-- flash messages -->
        {% for error_message in get_flashed_messages(category_filter=["error"]) %}
          <div class="alert alert-danger alert-dismissible">{{ error_message }}</div>
        {% endfor %}

        {% for success_message in get_flashed_messages(category_filter=["success"]) %}
          <div class="alert alert-success alert-dismissible">{{ success_message }}</div>
        {% endfor %}

        {% for info_message in get_flashed_messages(category_filter=["info"]) %}
          <div class="alert alert-info alert-dismissible">{{ info_message }}</div>
        {% endfor %}

        <!-- child template -->
        {% block content %}
        {% endblock %}

      </div>
      <div class="footer">
        <hr>
        <p>Patrick Kennedy - 2016</p>
      </div>
    </div><!-- /.container -->

    <!-- scripts -->
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </body>
</html>

project/recipes/templates/public_recipes.html
{% extends "layout.html" %}
{% block content %}
 
<div class="user-profile">
  <div class="page-header">
    <h2>Public Recipes</h2>
  </div>
 
  <table class="table table-striped" id="owned_stock_table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      {% for recipe in public_recipes %}
      <tr>
        <td>{{ recipe.recipe_title }}</td>
        <td>{{ recipe.recipe_description }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
 
{% endblock %}

project/recipes/templates/recipes.html
{% extends "layout.html" %}
{% block content %}
 
<div class="page-header">
  <h2>Recipes</h2>
</div>
<div class="row">
  <div class="col-md-4">
    <table class="table table-striped" id="owned_stock_table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        {% for recipe in recipes %}
        <tr>
          <td>{{ recipe.recipe_title }}</td>
          <td>{{ recipe.recipe_description }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
 
{% endblock %}

project/recipes/templates/user_recipes.html
{% extends "layout.html" %}
{% block content %}

<div class="user-profile">
  <div class="page-header">
    <h2>User Recipes</h2>
  </div>

  <table class="table table-striped" id="owned_stock_table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      {% for recipe in user_recipes %}
      <tr>
        <td>{{ recipe.recipe_title }}</a></td>
        <td>{{ recipe.recipe_description }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}